削除機能の実装
right1121/shiori pull request #11
Opened 2018-02-05 08:47 UTC by right1121

# なにをしたか
しおりを削除可能にした

# なぜしたか
ユーザーが不要になったしおりを削除できるようにするため

2018-02-05 10:13 UTC, ArakawaShintaro requested changes

2018-02-05 10:13 UTC, ArakawaShintaro commented on app/views/sioris/show.html.erb
> +
無駄な改行

2018-02-05 10:13 UTC, ArakawaShintaro commented on app/views/sioris/show.html.erb
> +    <%= link_to "しおりを削除する", @siori, method: :delete, data: { confirm: "本当に削除しますか?" } %>
ログイン中のユーザーかつ、そのしおりを作成した人物に絞るべきでは

2018-02-18 09:57 UTC, right1121 commented on app/views/sioris/show.html.erb
> +
削除しました。

2018-02-18 09:57 UTC, right1121 commented on app/views/sioris/show.html.erb
> +    <%= link_to "しおりを削除する", @siori, method: :delete, data: { confirm: "本当に削除しますか?" } %>
絞るようにします。

2018-02-28 05:16 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    Siori.find(params[:id]).destroy
```
Siori.find(params[:id])
```

をbefore_actionで呼び出せばDRYにかけると思います。
showアクションでも使用されているので。

例
```
def set_siori
  @siori = Siori.find(params[:id])
end
```

2018-02-28 05:16 UTC, ArakawaShintaro commented on app/models/user.rb
> +      travel_groups.find_by(siori_id: siori) ? travel_groups.find_by(siori_id: siori).owner : false
スペースが多いです。

2018-02-28 05:26 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    Siori.find(params[:id]).destroy
```
before_action :set_user, only: [:show, :destory]

private
  def set_siori
    @siori = Siori.find(params[:id])
  end
```
こうすることで、showでは `@siori = Siori.find(params[:id])` の記述がいらなくなるし
destroyでは、@sioriが使えるようになりますね

2018-02-28 05:35 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    Siori.find(params[:id]).destroy
修正しました！

2018-02-28 05:36 UTC, right1121 commented on app/models/user.rb
> +      travel_groups.find_by(siori_id: siori) ? travel_groups.find_by(siori_id: siori).owner : false
インデントですね。削除しました。

2018-02-28 05:38 UTC, ArakawaShintaro approved these changes
https://i.imgur.com/5nQ9ZUI.gif

2018-02-28 05:38 UTC, ArakawaShintaro approved these changes
[![LGTM](http://lgtm.in/p/cQt81oAoq)](http://lgtm.in/i/cQt81oAoq)

2018-02-28 05:42 UTC, merged