Follow
right1121/shiori pull request #13
Opened 2018-02-12 09:49 UTC by right1121

# なにをしたのか
しおりのフォロー・アンフォローできるようにした

#  なぜしたのか
ユーザーが他人のしおりも確認できるようにするため

2018-02-12 10:00 UTC, ArakawaShintaro requested changes

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +      @group.Owner = true
`@group.Owner` がすごく違和感感じます。
これって旅行グループに保存されている最後の人がオーナーになるってことでしょうか。

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +      @group.Owner = true
ここらへんのコードの意図をお聞きしたいですねぇ..

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/controllers/travel_groups_controller.rb
> +    siori = TravelGroup.find(params[:id]).siori_id
ここの変数名は`siori_id`の方が適切だと思います

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/models/user.rb
> +
改行が1つ多いですね

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/models/user.rb
> +    !travel_groups.find_by(siori_id: siori).Owner
ここも`Owner`クラスを読んでるの違和感感じます

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/views/sioris/_follow.erb
> +<%= form_for(current_user.travel_groups.build) do |f| %>
`current_user.travel_groups.build` はcontrollerで変数として渡したいですね。
viewに余計なロジックを書かない方がいいです

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/views/sioris/_unfollow.erb
> +<%= form_for(current_user.travel_groups.find_by(siori_id: @siori.id),
ここも同じく

2018-02-12 10:00 UTC, ArakawaShintaro commented on app/views/sioris/show.html.erb
> +      <% end %>
```
if user_signed_in? &&  current_user.following?(@siori)
```
とかでまとめられませんか？
if文のネストはみづらいです

2018-02-12 10:00 UTC, ArakawaShintaro commented on db/migrate/20180208085836_add_owner_to_travel_group.rb
> +    add_column :travel_groups, :Owner, :boolean, default: false, null: false
なぜ`owner`大文字なのですか？

2018-02-12 10:00 UTC, ArakawaShintaro commented on db/migrate/20180208085836_add_owner_to_travel_group.rb
> +    add_column :travel_groups, :Owner, :boolean, default: false, null: false
というか、全て`Owner`でアクセスしていたところの諸悪の根源はここだったのですね

2018-02-12 14:53 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +      @group.Owner = true
@siori.travel_groups.find_by(user_id: current_user)で指定できますね。
ちょっと理解がしきれてなかったです。修正します！

2018-02-12 14:53 UTC, right1121 commented on app/controllers/travel_groups_controller.rb
> +    siori = TravelGroup.find(params[:id]).siori_id
おっしゃる通りです。修正します。

2018-02-12 14:58 UTC, right1121 commented on app/models/user.rb
> +
削除します。

2018-02-12 15:01 UTC, right1121 commented on app/models/user.rb
> +    !travel_groups.find_by(siori_id: siori).Owner
修正しました。

2018-02-12 15:20 UTC, right1121 commented on app/views/sioris/_follow.erb
> +<%= form_for(current_user.travel_groups.build) do |f| %>
変数で処理します。

2018-02-12 15:20 UTC, right1121 commented on app/views/sioris/_unfollow.erb
> +<%= form_for(current_user.travel_groups.find_by(siori_id: @siori.id),
同上

2018-02-12 15:23 UTC, right1121 commented on app/views/sioris/show.html.erb
> +      <% end %>
まとめれました！

2018-02-12 16:03 UTC, right1121 commented on db/migrate/20180208085836_add_owner_to_travel_group.rb
> +    add_column :travel_groups, :Owner, :boolean, default: false, null: false
小文字に修正しました。

2018-02-13 01:14 UTC, ArakawaShintaro reviewed
1点だけコメントしました

2018-02-13 01:14 UTC, ArakawaShintaro commented on app/controllers/travel_groups_controller.rb
> +    siori = TravelGroup.find(params[:id]).siori_id
こちらの修正忘れていませんか？

2018-02-14 13:28 UTC, right1121 commented on app/controllers/travel_groups_controller.rb
> +    siori = TravelGroup.find(params[:id]).siori_id
忘れてます。。。修正します！

2018-02-17 12:35 UTC, ArakawaShintaro commented on app/models/user.rb
>    def not_owner?(siori)
not_owner?を作るよりも、owner?を作った方がシンプルだと思います。
もしowner?がfalseだったらnot_ownerだとおもうので。
いかがでしょうか。

2018-02-18 13:07 UTC, merged