Home画面の作成
right1121/shiori pull request #2
Opened 2017-12-16 07:28 UTC by right1121

Home画面にログイン機能を付けるため、deviceの設定を行いました。

2017-12-16 13:22 UTC, ArakawaShintaro commented on app/assets/javascripts/pages.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
不要なファイルは削除

2017-12-16 13:22 UTC, ArakawaShintaro commented on app/assets/stylesheets/pages.scss
> +// Place all the styles related to the Pages controller here.
同様です

2017-12-16 13:22 UTC, ArakawaShintaro commented on app/assets/stylesheets/pages.scss
> +// Place all the styles related to the Pages controller here.
rails g ~~~~ で自動生成しないように設定する

2017-12-16 13:22 UTC, ArakawaShintaro commented on app/helpers/pages_helper.rb
> +module PagesHelper
こちらも同様です

2017-12-16 13:22 UTC, ArakawaShintaro commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
いらないコメントアウトは消しましょう

2017-12-16 13:22 UTC, ArakawaShintaro commented on test/controllers/pages_controller_test.rb
> +require 'test_helper'
testファイルは消しましょう

2017-12-20 07:26 UTC, ArakawaShintaro requested changes

2017-12-20 07:26 UTC, ArakawaShintaro commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
pagesという名前は抽象的すぎて、なんのページ？ってなるのでやめたほうがいいですね

2017-12-20 09:01 UTC, right1121 commented on app/assets/javascripts/pages.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
不要ファイル削除しました。

2017-12-20 09:01 UTC, right1121 commented on app/assets/stylesheets/pages.scss
> +// Place all the styles related to the Pages controller here.
自動生成しないよう設定済みです。

2017-12-20 09:01 UTC, right1121 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
コメント削除しました。

2017-12-20 09:01 UTC, right1121 commented on test/controllers/pages_controller_test.rb
> +require 'test_helper'
testファイル削除しました。

2017-12-22 16:32 UTC, right1121 commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
pagesからlanding pageに名前を変更しました。

2017-12-29 15:32 UTC, closed without merging