ヘッダーの作成
right1121/shiori pull request #21
Opened 2018-02-22 18:31 UTC by right1121

# なにをしたのか
ヘッダーの作成

# なぜしたのか
ナビゲーションの代わり

2018-02-24 15:55 UTC, ArakawaShintaro approved these changes
デザイン系タスクはキャプチャを貼ってください

2018-02-24 15:57 UTC, right1121 commented
![image](https://user-images.githubusercontent.com/22765090/36632196-e00f1130-19c6-11e8-86cd-c98c99e1f1ba.png)

2018-02-25 04:44 UTC, ArakawaShintaro reviewed
ヘッダーの左にサービス名があった方がいいと思うのですが、どうでしょうか。

2018-02-26 14:28 UTC, right1121 commented
確かにあったほうがかっこいいです！早速実装します。

2018-02-28 07:30 UTC, ArakawaShintaro requested changes

2018-02-28 07:30 UTC, ArakawaShintaro commented on app/views/layouts/application.html.erb
> +            			<a class="navbar-brand" href="#">しおり</a>
`link_to` を使いましょう 👍 
あと、サービス名これで本当にいいんですかね？w

2018-03-02 14:25 UTC, ArakawaShintaro approved these changes

2018-03-02 14:27 UTC, merged