しおり一覧の作成
right1121/shiori pull request #5
Opened 2018-01-06 14:38 UTC by right1121

# なにをしたか
ユーザーが閲覧可能なしおりの一覧を表示する

# なぜしたか
作成したしおりを確認できるようにするため

2018-01-07 08:09 UTC, ArakawaShintaro reviewed
ひとまずみました

2018-01-07 08:09 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    @user = User.find_by(id: current_user.id)
ここって結局current_userですよね？
なぜ、わざわざfind_byしてきているのですか？

2018-01-07 08:09 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +  def create
アクションの順番は7つのアクションの順番でやってほしいですね
index show new create edit update destroy

2018-01-07 08:09 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    @sioris = Siori.where()
whereは条件がなかったらだめなきがするんですが、
これだと何が取得できていますか？

2018-01-07 08:09 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    @user = User.find_by(id: current_user.id)
もしviewで使ってるなら、viewでcurrent_userを書けばわざわざインスタンス変数にする必要もないですし

2018-01-07 08:09 UTC, ArakawaShintaro commented on app/views/sioris/index.erb
> +<% end %>
最後は空の改行をいれましょう
赤いマークがあるところは全てです

2018-01-07 08:09 UTC, ArakawaShintaro commented on app/views/sioris/new.html.erb
> +<p>Find me in app/views/sioris/new.html.erb</p>
ここもマークがでていますね

2018-01-07 08:43 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    @user = User.find_by(id: current_user.id)
おっしゃる通りです。無駄な記述ですね。削除して修正します！

2018-01-07 08:47 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +  def create
承知しました。並べ替えます。

2018-01-07 08:49 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    @sioris = Siori.where()
そのうち使うかな。と思って放置している状態です。このブランチでは関係ないので削除しておきます！

2018-01-07 08:49 UTC, right1121 commented on app/views/sioris/index.erb
> +<% end %>
承知しました。すべて修正します。

2018-01-07 08:50 UTC, right1121 commented on app/views/sioris/new.html.erb
> +<p>Find me in app/views/sioris/new.html.erb</p>
修正します！

2018-01-10 13:33 UTC, ArakawaShintaro requested changes

2018-01-10 13:33 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +  def show
必要なアクションのみでいいです

2018-01-10 13:33 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +  before_action :authenticate_user!
アクションの制限はかけなくていいのですが？

2018-01-10 13:33 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    @sioris = current_user.sioris
```
@sioris = current_user.siorios if current_user
# ログインしていない時の処理
```

2018-01-10 13:33 UTC, ArakawaShintaro commented on app/views/sioris/index.erb
> +<p><%= current_user.id %></p>
```
<% if current_user %>
  ~~~
<% end %>
```

2018-01-10 13:33 UTC, ArakawaShintaro commented on app/views/sioris/show.html.erb
> +<h1>Sioris#ahow</h1>
ahow!?!?!

2018-01-10 13:33 UTC, ArakawaShintaro commented on app/views/sioris/show.html.erb
> +<p><%= @sioris.id %></p>
変数が定義されていないです

2018-01-28 16:52 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +  before_action :authenticate_user!
showのみ閲覧可能にします。indexはどこまで表示させるのかキリがないためログインしているユーザーのみが閲覧できるようにします。

2018-01-28 16:54 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    @sioris = current_user.sioris
indexはログインユーザーのみ閲覧可能にします！

2018-01-28 16:54 UTC, right1121 commented on app/views/sioris/show.html.erb
> +<h1>Sioris#ahow</h1>
修正します！

2018-01-28 16:55 UTC, right1121 commented on app/views/sioris/show.html.erb
> +<p><%= @sioris.id %></p>
不要な変数ですね。。。削除しておきます。

2018-01-28 16:55 UTC, right1121 commented on app/views/sioris/index.erb
> +<p><%= current_user.id %></p>
index以外で使用します！

2018-02-05 06:09 UTC, right1121 commented
![image](https://user-images.githubusercontent.com/22765090/35790600-921a8fda-0a86-11e8-9cac-5f39073bb009.png)

2018-02-05 07:01 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +  before_action :authenticate_user!
こちらはどうなっているのでしょうか

2018-02-05 08:19 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +  before_action :authenticate_user!
設定し忘れていました！修正します。

2018-02-05 08:42 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +  before_action :authenticate_user!, except: [:show]
ん、これだとshow以外はログインユーザー必須となる気がしますが

2018-02-12 09:50 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +  before_action :authenticate_user!, except: [:show]
URLを知っていればログインしていなくても閲覧できるようにするためです。

2018-02-12 10:02 UTC, ArakawaShintaro approved these changes
PRの粒度が大きすぎますね(>_<)
レビューしづらいです(>_<)
動作に問題がなければLGTMで！

2018-02-12 17:30 UTC, merged