[WIP]しおり作成機能の実装
right1121/shiori pull request #6
Opened 2018-01-06 14:40 UTC by right1121

# なにをしたか
ユーザーがしおりを作成できるようにする。

# なぜしたか
ユーザーがしおりを作成できるようにするため

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    @user = current_user
変数に入れる必要がないです

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    @siori = Siori.new(siori_params)
```
current_user.sioris.new(siori_params)
```

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    if @user.save
userが保存されているみたいで違和感があります

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +  private
```
private

  def hoge
  end
```

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/helpers/add_travel_day_helper.rb
> +    def link_to_add_day(name, f, association, options={})
nested_formとか使ったら楽になれるかもです

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/views/sioris/_form.html.erb
> +</div>
改行

2018-01-10 13:58 UTC, ArakawaShintaro commented on app/views/sioris/_form.html.erb
> +  <%= render partial: "travel_day_form", locals: {f: f } %>
```
{ f: f }
```

2018-01-11 03:47 UTC, right1121 commented on app/views/sioris/_form.html.erb
> +</div>
修正しました。

2018-01-11 03:47 UTC, right1121 commented on app/views/sioris/_form.html.erb
> +  <%= render partial: "travel_day_form", locals: {f: f } %>
修正しました。

2018-01-11 03:47 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +  private
修正しました。

2018-01-14 13:32 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    @siori = Siori.new(siori_params)
current_user.sioris.new(siori_params)に変更しました。

2018-01-14 13:33 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    @user = current_user
変数削除しました。

2018-01-14 13:33 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    if @user.save
インスタンス変数を@sioriにしました。

2018-01-14 13:42 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    if current_user.sioris.create(siori_params)
ここって、事前にsiori保存してますが
再度保存するんですか？

2018-01-14 13:42 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +    if @siori.save
やっぱそうですよねw
ここは、求めてる挙動にきちんとなっていますか？

2018-01-14 13:48 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    if @siori.save
挙動は大丈夫です。しっかりと紐づけて保存できています。

2018-01-14 13:49 UTC, right1121 commented on app/controllers/sioris_controller.rb
> +    if current_user.sioris.create(siori_params)
コードが古い気がします！最新は
```
@siori = current_user.sioris.new(siori_params)

if @siori.save
  current_user.sioris << @siori
  redirect_to sioris_url
else
```
になっているかと！

2018-01-15 12:15 UTC, ArakawaShintaro requested changes

2018-01-15 12:15 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +      current_user.sioris << @siori
トランザクションをしようした方がいいです。

2018-01-15 12:15 UTC, ArakawaShintaro commented on app/controllers/sioris_controller.rb
> +      render 'new'
念頭に置いとくぐらいでいいんですが、フラッシュメッセージがあった方がUI / UX的にいいですね。

2018-01-26 15:42 UTC, right1121 commented on app/helpers/add_travel_day_helper.rb
> +    def link_to_add_day(name, f, association, options={})
rails5に対応していなかったため、cocoonを導入しました！

2018-01-26 15:48 UTC, ArakawaShintaro reviewed
細かいですが見ました

2018-01-26 15:48 UTC, ArakawaShintaro commented on app/assets/javascripts/cocoon_form.js.coffee
> +
改行が必要です

2018-01-26 15:48 UTC, ArakawaShintaro commented on app/controllers/application_controller.rb
> +
細かいですがここの改行はいらないと思います

2018-01-26 15:48 UTC, ArakawaShintaro commented on app/views/sioris/_tourist_detail_fields.erb
> +</div>
改行が必要です

2018-01-26 15:48 UTC, ArakawaShintaro commented on config/routes.rb
> +
ここは改行不要です

2018-01-27 13:14 UTC, right1121 commented on app/controllers/application_controller.rb
> +
削除しました！

2018-01-27 13:14 UTC, right1121 commented on app/assets/javascripts/cocoon_form.js.coffee
> +
改行しました。

2018-01-27 13:14 UTC, right1121 commented on app/views/sioris/_tourist_detail_fields.erb
> +</div>
改行しました。

2018-01-27 13:14 UTC, right1121 commented on config/routes.rb
> +
改行削除しました。

2018-01-31 12:52 UTC, ArakawaShintaro approved these changes

2018-01-31 13:35 UTC, merged